-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
--
-- -- set termguicolors to enable highlight groups
-- vim.opt.termguicolors = true
--
-- require("nvim-tree").setup({
--   renderer = {
--     icons = {
--       show = {
--         git = true,
-- 	file = true,
-- 	folder = true,
-- 	folder_arrow = true,
--       },
--       glyphs = {
--         git = {
--           unstaged = "✗",
--           staged = "✓",
--           unmerged = "⌥",
--           renamed = "➜",
--           untracked = "★",
--           deleted = "⊖",
--           ignored = "◌",
--         },
--       },
--     },
--   },
-- })
--
